import type { LeaderResult, PartyOption, RegionOption, SortOption } from "./types";

export const regionOptions: RegionOption[] = [
  { id: "all", label: "All India" },
  { id: "uttar-pradesh", label: "Uttar Pradesh" },
  { id: "maharashtra", label: "Maharashtra" },
  { id: "west-bengal", label: "West Bengal" },
  { id: "tamil-nadu", label: "Tamil Nadu" },
  { id: "karnataka", label: "Karnataka" },
  { id: "bihar", label: "Bihar" },
  { id: "gujarat", label: "Gujarat" },
  { id: "rajasthan", label: "Rajasthan" },
];

export const partyOptions: PartyOption[] = [
  { id: "bjp", label: "BJP" },
  { id: "inc", label: "INC" },
  { id: "aitc", label: "AITC" },
  { id: "dmk", label: "DMK" },
  { id: "tdp", label: "TDP" },
  { id: "aap", label: "AAP" },
  { id: "others", label: "Others" },
];

export const sortOptions: SortOption[] = [
  { id: "popularity_desc", label: "Popularity (High to Low)" },
  { id: "votes_desc", label: "Total Vote Count" },
  { id: "name_asc", label: "Name (A-Z)" },
];

export const leaderResults: LeaderResult[] = [
  {
    id: "modi",
    name: "Narendra Modi",
    role: "Prime Minister",
    party: "BJP",
    region: "Union Government",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Narendra",
    sentiment: 72.8,
    trendDirection: "up",
    trendValue: "2.4%",
    votesToday: "1,240,512",
  },
  {
    id: "rahul",
    name: "Rahul Gandhi",
    role: "MP, Wayanad",
    party: "INC",
    region: "Main Opposition",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul",
    sentiment: 48.2,
    trendDirection: "up",
    trendValue: "1.8%",
    votesToday: "840,122",
  },
  {
    id: "mamata",
    name: "Mamata Banerjee",
    role: "Chief Minister",
    party: "AITC",
    region: "West Bengal",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mamata",
    sentiment: 52.4,
    trendDirection: "down",
    trendValue: "0.5%",
    votesToday: "420,019",
  },
  {
    id: "kejriwal",
    name: "Arvind Kejriwal",
    role: "Chief Minister",
    party: "AAP",
    region: "Delhi",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arvind",
    sentiment: 61.8,
    trendDirection: "up",
    trendValue: "3.2%",
    votesToday: "310,488",
  },
  {
    id: "yogi",
    name: "Yogi Adityanath",
    role: "Chief Minister",
    party: "BJP",
    region: "Uttar Pradesh",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Yogi",
    sentiment: 78.4,
    trendDirection: "up",
    trendValue: "1.5%",
    votesToday: "512,940",
  },
  {
    id: "nitish",
    name: "Nitish Kumar",
    role: "Chief Minister",
    party: "JD(U)",
    region: "Bihar",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nitish",
    sentiment: 55.6,
    trendDirection: "up",
    trendValue: "2.1%",
    votesToday: "215,301",
  },
];
